[package]
name = "nanoq"
version = "0.1.1"
authors = ["esteinig <eikejoachim.steinig@my.jcu.edu.au>"]
description = "Minimal but speedy quality control for nanopore reads"
documentation = "https://github.com/esteinig/nanoq"
homepage = "https://github.com/esteinig/nanoq"
repository = "https://github.com/esteinig/nanoq"
readme = "README.md"
keywords = ["nanopore", "quality", "ont", "filter", "read"]
categories = ["science"]
license = "MIT"
edition = "2018"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
clap = "2.33.0"
bio = "0.30.0"
libm = "0.2.1"
needletail = "0.4"