{% set version = "0.8.0" %}

# conda build -c esteinig -c conda-forge .

package:
  name: nanoq
  version: {{ version }}

source:
  path: .

build:
  number: 0

requirements:
  build:
      - {{ compiler('cxx') }}
  host:
      - rust>=1.53
  run:
      - rust>=1.53
test:
  commands:
    - nanoq -h

about:
  home: 'https://github.com/esteinig/nanoq'
  license: MIT
  license_file: LICENSE
  summary: 'Minimal but speedy quality control and summaries of nanopore reads'

