{% set version = "0.8.1" %}
{% set name = "nanoq" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/esteinig/{{ name }}/archive/{{ version }}.tar.gz
  sha256: a6548374db1439a6b325c872b5fe94d5fdaffbd10a3c6ede6a335f4c3293fa32

build:
  number: 0

requirements:
  build:
    - rust >=1.53
    - {{ compiler('c') }}              # [not win]

test:
  commands:
    - nanoq -h

about:
  home: https://github.com/esteinig/nanoq
  license: MIT
  summary: Ultra-fast quality control and summary reports for nanopore reads
  license_file: LICENSE

extra:
  recipe-maintainers:
    - esteinig
    


